### ISSUE TITLE
fix the issues

### ISSUE THREAD

**Issue by FreakWolf** [Sachin6189/Issue-Tracking-System#20]
1. Filter the data in the table accoring to the latest entry.
2. Make the contact text area to take only digits taht to 10 digits or else give error message.
3. Apply Date Filter too.
4. Show maximum 10 Data entry on the starting page.
5. Add Description and Upload file(mostly image) in json tooo.

**Comment by Sachin6189** [comment]
Everything added except date filter and description and upload file issue.

**Comment by FreakWolf** [comment]
tune kar diya changes ??

**Comment by Sachin6189** [comment]
yuup.....but decription wala nhi kiye or upload file wala bhi nhi kiye.
