### ISSUE TITLE
Modify the code for Reuseability and proper structure

### ISSUE THREAD

**Issue by FreakWolf** [Sachin6189/Issue-Tracking-System#3]
Make the mentioned changes in the code:
1. Make the current Login.js page into 3 components named Login.js, Logo.js and LoginForm.js
2. Then first learn about [async/await](https://javascript.info/async-await) functon after that learn about [Axios](https://www.npmjs.com/package/axios) and [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), what is the difference between them.
3. Use axios to fetch api from the backend and leave the handling for the future and use POST method with axios, search it on the above link provided how to use POST method.
4. Make a function for validaton and use that function in the handleSubmit function.
5. Before uing the validation library reacd about it first from npm official website [Validator](https://www.npmjs.com/package/validator).

**Comment by Sachin6189** [comment]
Learn GET also(for me, not for you.😁😁😁😁)
